client.println("<!DOCTYPE html>");
client.println("<html lang='en'>");
client.println("<head>");
client.println("<meta charset='UTF-8'>");
client.println("<meta http-equiv='X-UA-Compatible' content='IE=edge'>");
client.println("<meta name='viewport' content='width=device-width, initial-scale=1.0'>");
client.println("<style>");
client.println("* {");
client.println("background-color: rgb(255,207,241);");
client.println("}");
client.println("p{");
client.println("text-decoration: underline;");
client.println("font-style: italic;");
client.println("font-weight: bold;");
client.println("color: rgba(182, 11, 11, 0.993);");
client.println("font-size : 36px;");
client.println("}");
client.println("button{");
client.println("background-color: rgb(60, 145, 160);");
client.println("padding: 10px;");
client.println("margin: 10px;");
client.println("border-radius: 30%;");
client.println("border: 3px solid rgb(0, 0, 0);");
client.println("height: 70px;");
client.println("width: 120px;");
client.println("}");
client.println("button:hover {");
client.println("cursor: pointer;");
client.println("color: rgb(214, 81, 176);");
client.println("background-color: rgb(251, 255, 0);");
client.println("}");
client.println("</style>");
client.println("<title>Document</title>");
client.println("</head>");
client.println("<body>");
client.println("<p> État de la led : Off<br> </p>");
client.println("<button>Allumer<a href='/LED=ON''></a></button>");
client.println("<button>Éteindre<a href='/LED=OFF''></a></button>");
client.println("<!-- <a href='/LED=ON''><button>Allumer </button></a>");
client.println("<a href='/LED=OFF''><button>Eteindre </button></a><br /> -->");
client.println("</body>");
client.println("</html>");
