client.println("<!DOCTYPE html>");
client.println("<html lang='en'>");
client.println("<head>");
client.println("<meta charset='UTF-8'>");
client.println("<meta http-equiv='X-UA-Compatible' content='IE=edge'>");
client.println("<meta name='viewport' content='width=device-width, initial-scale=1.0'>");
client.println("<style>");
client.println("body {");
client.println("background-color: rgb(255,207,241);");
client.println("}");
client.println("p{");
client.println("text-decoration: underline;");
client.println("font-style: italic;");
client.println("font-weight: bold;");
client.println("color: rgba(182, 11, 11, 0.993);");
client.println("font-size : 36px;");
client.println("");
client.println("}");
client.println("button{");
client.println("background-color: rgb(60, 145, 160);");
client.println("padding: 10px;");
client.println("margin: 10px;");
client.println("border-radius: 30%;");
client.println("border: 3px solid rgb(0, 0, 0);");
client.println("height: 70px;");
client.println("width: 120px;");
client.println("}");
client.println("button:hover {");
client.println("cursor: pointer;");
client.println("color: rgb(214, 81, 176);");
client.println("background-color: rgb(251, 255, 0);");
client.println("}");
client.println("input{");
client.println("");
client.println("}");
client.println("a {");
client.println("color: inherit;");
client.println("text-decoration: none;");
client.println("}");
client.println("input[type='color'] {");
client.println("margin-left: 40px;");
client.println("}");
client.println("</style>");
client.println("<title>Document</title>");
client.println("</head>");
client.println("<body>");
client.println("<p> État de la led : Off<br> </p>");
client.println("<button><a href='/LED=OFF'>OFF</a></button>");
client.println("<br>");
client.println("");
client.println("<input type='color' onChange='printColor(event)'><br>");
client.println("<script> //JavaScript");
client.println("function printColor(ev) {");
client.println("const color = ev.target.value");
client.println("const r = parseInt(color.substr(1,2), 16)");
client.println("const g = parseInt(color.substr(3,2), 16)");
client.println("const b = parseInt(color.substr(5,2), 16)");
client.println("window.location = `?r${r}g${g}b${b}`");
client.println("}");
client.println("</script>");
client.println("<br>");
client.println("");
client.println("</body>");
client.println("</html>");
