client.println("<!DOCTYPE html>");
client.println("<html lang='en'>");
client.println("<head>");
client.println("<meta charset='UTF-8'>");
client.println("<meta http-equiv='X-UA-Compatible' content='IE=edge'>");
client.println("<meta name='viewport' content='width=device-width, initial-scale=1.0'>");
client.println("<style>");
client.println("body, input {");
client.println("background-color: rgb(107, 169, 180);");
client.println("}");
client.println("p {");
client.println("margin-left: 15px;");
client.println("text-decoration: underline;");
client.println("font-style: italic;");
client.println("font-weight: bold;");
client.println("color: rgba(0, 0, 0, 0.993);");
client.println("font-size : 36px;");
client.println("}");
client.println("button{");
client.println("background-color: rgb(240, 182, 234);");
client.println("padding: 10px;");
client.println("margin: 20px;");
client.println("border-radius: 30%;");
client.println("border: 3px solid rgb(102, 38, 88);");
client.println("height: 70px;");
client.println("width: 120px;");
client.println("}");
client.println("button:hover {");
client.println("cursor: pointer;");
client.println("color: rgb(214, 81, 176);");
client.println("background-color: rgb(255, 0, 0);");
client.println("}");
client.println("a {");
client.println("color: inherit;");
client.println("text-decoration: none;");
client.println("}");
client.println("input#color1 {");
client.println("-webkit-appearance: none;");
client.println("-moz-appearence: none;");
client.println("appearance: none;");
client.println("width: 100px;");
client.println("height: 100px;");
client.println("background-color: transparent;");
client.println("border: none;");
client.println("cursor: pointer;");
client.println("margin-left: 30px;");
client.println("}");
client.println("input#color1::-webkit-color-swatch {");
client.println("border-radius: 50%;");
client.println("border: none;");
client.println("}");
client.println("</style>");
client.println("<title>Document</title>");
client.println("</head>");
client.println("<body>");
client.println("<p> Leds Strip </p>");
client.println("<button><a href='/LED=ON'>ON</a></button><br>");
client.println("<input id='color1' type='color' value='#FFFFFF' onChange='printColor(event)'><br>");
client.println("<button><a href='/LED=OFF'>OFF</a></button>");
client.println("<script> //JavaScript");
client.println("function printColor(ev) {");
client.println("const color = ev.target.value");
client.println("const r = parseInt(color.substr(1,2), 16)");
client.println("const g = parseInt(color.substr(3,2), 16)");
client.println("const b = parseInt(color.substr(5,2), 16)");
client.println("window.location = `?r${r}g${g}b${b}`");
client.println("}");
client.println("</script>");
client.println("<br>");
client.println("</body>");
client.println("</html>");
